### ISSUE TITLE
"working_path" not found

### ISSUE THREAD

**Issue by etmckinley** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#1]
I'm getting an error running the code on the sample data at line 133 in BISCUIT_IMM_Gibbs_MCMC_parallel.R:

path <- working_path;

working_path is not defined. I replaced it with 

path=getwd()

and it seems to run. Just wanted to let you know and make sure that fix doesn't break anything else.

One other thing is that in the final line of BISCUIT_main.R, f1 is not defined.

**Comment by sandhya212** [comment]
In the Readme.md, under 'How to run the code', see #3. You need to populate the working_path to where the code resides. If getwd() also returns where your code is, you are good to go. 

f1 is defined in BISCUIT_extras.R and BISCUIT_extras_onegenebatch.R. The last line in BISCUIT_main.R is called at the very end, to populate an output file with run parameters/stats etc. 

Let me know if you have further questions.
