### ISSUE TITLE
endless Rprof.out output?

### ISSUE THREAD

**Issue by dschrein** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#10]
i am running this on a cluster with 8 cores and 4 GB RAM per core. it's about 3K cells and about 10K genes

after 3 days, Rprof.out is 4.3 GB and every line is like this:

$ tail -3 Rprof.out 
:1641588:41371563:101158008:0:"solve.default" "solve" "standardGeneric" "solve" "IMM.MCMC" "main.fun" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "fun" "do.call" "docall" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "slaveLoop" "eval" "eval" "eval" "eval" "eval.parent" "local" 
:1641588:41371563:101158008:0:"solve.default" "solve" "standardGeneric" "solve" "IMM.MCMC" "main.fun" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "fun" "do.call" "docall" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "slaveLoop" "eval" "eval" "eval" "eval" "eval.parent" "local" 
:1641588:41371563:101158008:0:"solve.default" "solve" "standardGeneric" "solve" "IMM.MCMC" "main.fun" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatch

what else can i check? none of the other files have been recently modified since the first day.

**Comment by sandhya212** [comment]
I had switched off printing into Rprof.out just to speed up the runs. So this Rprof.out would not help debugging. How is your code now? We have tried the code on 40+ cores. Perhaps this is why the code is slow for you. We have successfully run 3K cells and about 10K genes on AWS instances.

**Comment by dschrein** [comment]
i submitted this using SLURM to a scientific computing cluster, chose 10 cores each with 6 GB RAM, and let it run for a week. i guess i will try with more.

however, very little of the RAM is actually used:

Memory Utilized: 5.53 GB
Memory Efficiency: 9.21% of 60.00 GB

and it is not just slow - it actually just seems to stop. basically the processes just seem to end with batch 47 and nothing else is written except to Rprof.out: 

```
[1] "Calculating the Fiedler vector of the data"
[1] "Ensuring entire data is numeric and then log transforming it"
[1] "numcells is 3087"
[1] "numgenes is 9715"
[1] "Number of gene batches is 194"
[1] "Number of gene subbatches is 2"
[1] "Ensuring user-specified data is numeric"
[1] "Computing t-sne projection of the data"
[1] "Monitor log.txt and outputs/plots/ folder for outputs"
[1] "floor(num_gene_batches/num_gene_sub_batches): 97"
[1] "MCMC begins"
[1] "Begin parallel processing of gene splits"
[1] "Beginning of batch  1"
[1] "End of batch  1"
...
[1] "End of batch  42"
[1] "Beginning of batch  43"
[1] "End of batch  43"
[1] "Beginning of batch  44"
[1] "End of batch  44"
[1] "Beginning of batch  45"
[1] "End of batch  45"
[1] "Beginning of batch  46"
[1] "End of batch  46"
[1] "Beginning of batch  47"
```

**Comment by sandhya212** [comment]
Ok, so this seems like the code is running but is waiting for more memory. Each batch is implementing a Gibbs sampler where all the distributional parameters are being sampled. What is the 'gene_batch' set to in your start_file.R? Consider increasing it upto 50 to reduce the number of batches. 

We have run a typical dataset (similar to your data size) on an AWS r4.16xlarge instance with ~40 cores. The initial step where the Fiedler vector is calculated is the one that takes a lot of memory as you have to invert a genes x genes matrix. But then in each Gibbs batch, you would not need all this memory, but need sufficient memory to run the inference. 
 
Hope this helps.

**Comment by dschrein** [comment]
gene_batch is 50

i'll try with more cores/memory --> is there a way to estimate the system requirements from the # of genes/cells?

how long should a run with data of this size take with 40 cores?  (obviously the speed of each core is a factor, but a general ballpark figure)

what i'm also not sure about is detectCores() -- will it actually detect the number of available cores? maybe i should just hard-code num_cores.

**Comment by sandhya212** [comment]
> Consider increasing your gene_batch to 150
> Your dataset should take less than a day with 60 cores on AWS
> Hardcoding number of cores to be used is also possible
