### ISSUE TITLE
running

### ISSUE THREAD

**Issue by sunynping** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#11]
Error in socketSelect(socklist) : not a list of sockets???

**Comment by sandhya212** [comment]
This is too little information to provide any help. When did you get this?

**Comment by sunynping** [comment]
When i run source("start_file.R")




------------------ Original ------------------

**Comment by sandhya212** [comment]
Please follow the steps in the Readme file: https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/blob/master/Readme.md
