### ISSUE TITLE
Error in plot.xy(xy, type, ...) : object 'z_true' not found

### ISSUE THREAD

**Issue by YiqunCao** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#12]
Hi,
When I run start_file.R on around 3000 cells, the above error reported. How could I continue? Thank you.
Best,
Elaine

**Comment by sandhya212** [comment]
Please follow the steps mentioned in the Readme file: https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/blob/master/Readme.md
