### ISSUE TITLE
input and output 

### ISSUE THREAD

**Issue by freepluslq** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#14]
Two questions.

1.What should be the correct format of input file if "z_true_labels_avl" set be TRUE?
First 4 lines of your example file 'expression_mRNA_17-Aug-2014.txt' is the cell annotation, is that will be recognized as the 'true labels of cells' mentioned in readme file? 

2. I know the gene id through "gene_selected.csv" one of output files,but what about the cell id selected by program? The "post_imputed_tSNE_coord.txt" only provide the tSNE coordinates of cells but I need corresponding cell-id,how can I find it ?

Thanks.

**Comment by sandhya212** [comment]
1. You may use the cell annotation as the true label as well. But in this example dataset, the true labels were provided from the 8th row onwards. Refer to Line 45 of (https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/blob/master/BISCUIT_process_data.R) where z_true is collected as z_true <- as.numeric(factor(unlist(full.data[8,][3:(dim(full.data)[2])]))). 

2. We do not shuffle or permute the rows (cells). So the rows stay the same from beginning till the end.
