### ISSUE TITLE
A problem which is likely due to the parallel processing

### ISSUE THREAD

**Issue by TTTPOB** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#15]
Every time I run the code, when the program reaches here "Beginning of Batch 1", and after a few hours it will end up with this "Error in unserialize(socklist[[n]]) : 'connection' must be a connection"
![](https://ws1.sinaimg.cn/large/6e173d3cgy1fursfc79fbj21pp145adl.jpg)
but at the same time, the parallel processes are still running, 
![](https://ws1.sinaimg.cn/large/6e173d3cgy1fursgwkbzqj21pp145b29.jpg)
so I don't know if the error actually put an end to the running program.
By the way, the cores to use paramater in "start_file.R" seems make no difference. I set it to 18 this time but it still consumes nearly 100 cores while parallel processing.

**Comment by sandhya212** [comment]
Even though the parallel processes (worker sockets) are spun, they are still waiting for code to be executed on them. One reason for this error is that when the main socket was reaching out to a worker socket to start code execution in that socket, the worker just died, thus terminating the socket connection. There can be other reasons too and this error is very system-specific. 

Have you been able to run the code on a smaller set of genes (numgenes = 5000)? 

If you have started the code on a fresh instance and then set the cores to a specific number, only that many are used. If you set it after having run the code and without having closed all sockets, then it is likely that setting the #cores would not help.

**Comment by TTTPOB** [comment]
Thanks, trying it.
And I am wandering when using part of genes/cells, how do you subset them? Random or according to some measurement?
And by saying setting core numbers won't help, I mean that there AREthat as many children processes as I set in #cores, but each of them uses as many as cores, not just one core.

**Comment by sandhya212** [comment]
You can choose all your cells. It is the gene space that is huge. If you choose, say 1000 genes, then all your 14K genes will be used by the Fiedler vector to give a sorted gene array from which the first 1000 will be selected. 
You can try the code on a smaller gene (and cell) space to first ensure you can get the code to run.

**Comment by TTTPOB** [comment]
Thanks, trying. I have tried the demo data before with no error occured. Hope this will work too.

**Comment by TTTPOB** [comment]
here is my start_file.R, and the error message which remains the same as last time.
should I try to run it with a single core?
![image](https://user-images.githubusercontent.com/19909103/45129501-9498b480-b1b6-11e8-9161-910f0aff44ea.png)
![image](https://user-images.githubusercontent.com/19909103/45129524-ada16580-b1b6-11e8-8812-1e35ec2a3935.png)

**Comment by YuxuanZheng94** [comment]
I have the same problem.

**Comment by sandhya212** [comment]
I suspect this is due to problems with certain R packages (especially those dealing with parallel processes) not being backward compatible. 
1. What is the R version. (At the R terminal, >R.version.string). I get 'R version 3.4.1 (2017-06-30)'
2. Also check >write.csv(installed.packages(),"packageManifest.csv"). 
Open this .csv and check what the versions of R packages are: doParallel, chron, doSNOW, foreach. For comparison purposes, I have attached what I use. 
![screen shot 2018-09-06 at 8 51 11 am](https://user-images.githubusercontent.com/14878558/45158573-5e593600-b1b2-11e8-9edf-730bdffd06bf.png)
![screen shot 2018-09-06 at 8 55 52 am](https://user-images.githubusercontent.com/14878558/45158577-60bb9000-b1b2-11e8-8506-65e430cabff3.png)

**Comment by YuxuanZheng94** [comment]
I have used the R and R packages whose versions are as same as yours. And I have used only one core to run the code. However, the error is still existing. 
After executing the following steps:

`...
[1] "Beginning of batch  1"
[1] "End of batch  1"
[1] "Beginning of batch  2"`

the error information gives rise to:

`Error in unserialize(socklist[[n]]) : error reading from connection
Calls: source ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted`

If I used multi-cores,  the error information gives rise to:

`Error in unserialize(socklist[[n]]) : error reading from connection
Calls: source ... recvOneData -> recvOneData.SOCKcluster -> unserialize
Execution halted`

**Comment by sandhya212** [comment]
This is a system-generated error wrapped by R like so. And there can be many reasons why this can happen. 
I am not entirely sure why this is happening if you are using the same R and package versions. Could you also inform where you are running the code on - OS, machine specifications etc? What data is this?

**Comment by parry0106** [comment]
Hi,@sandhya212 
I have the same question above.just as the fllowing picture
![image](https://user-images.githubusercontent.com/49709170/57191611-23361f00-6f5a-11e9-805b-ef3a63f3c375.png)
The parameter is the fllowing picture.
![image](https://user-images.githubusercontent.com/49709170/57191621-4660ce80-6f5a-11e9-9b50-5aaf46535a5a.png)
the output is the fllowing picture.
![image](https://user-images.githubusercontent.com/49709170/57191651-888a1000-6f5a-11e9-96d3-c8928c3927e4.png)

The R version is R 3.5.1
How can I deal with this problem?
Thank you very much.

**Comment by HarshaRagyari** [comment]
Hi..am facing the same issue in linux on aws platform.. what is the possible solution for this? Thanks a ton in advance.

**Comment by sandhya212** [comment]
Hi @HarshaRagyari, we have never come across this error. What AWS instance are you using to run the code?

**Comment by mb706** [comment]
Sorry to reply to such an old issue, but I ran across this issue and investigated it, and I wanted to leave this here for other people googling the same problem. What happens is that the `snow` package makes a wrong assumption about how R's `socketSelect()` function works. The solution that worked for me was to patch the `snow:::recvOneData.SOCKcluster` function by runnign the following code in the main R session:
```r
ns <- asNamespace("snow")
f <- get("recvOneData.SOCKcluster", envir = ns)
env <- new.env(parent = environment(f))
env$socketSelect <- function(...) {
  result <- base::socketSelect(...)
  if (!any(result)) return(logical(0))
  result
}
environment(f) <- env
unlockBinding("recvOneData.SOCKcluster", ns)
assign("recvOneData.SOCKcluster", f, envir = ns)
lockBinding("recvOneData.SOCKcluster", ns)
```
