### ISSUE TITLE
Error in as.vector(data) : no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by YuxuanZheng94** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#16]
When I performed BISCUIT in the step as following, the code gave rise to an error "Error in as.vector(data) : no method for coercing this S4 class to a vector". Would you help me with this problem?
Thank you!

"""
......
[1] "Monitor debug_CM.txt for parallel process diagnostics and log_CM.txt for MAP progression"
[1] "Time for creating the MAP estimates"
Time difference of 6.888685 secs
[1] "Resample moments per cluster"
[1] "cluster is 1"
"""

**Comment by sandhya212** [comment]
What is the value of mean_num_clusters?
You have run at least until line 315 here (https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/blob/master/Confusion_matrix_stitch_parallel_MAP.R).

**Comment by YuxuanZheng94** [comment]
mean number of clusters is 25

**Comment by sandhya212** [comment]
If you still have the instance open, could you please step the code from 315 till 336 and let me know at which line you got this error.
