### ISSUE TITLE
Error in { : task 10 failed - "missing value where TRUE/FALSE needed"

### ISSUE THREAD

**Issue by kupadhya2** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#17]
Hi Sandhya, 

Please see below error: 

> for(r_all in 1:runs.all){
+     
+     print(paste("Beginning of batch ",r_all));
+     
+     results.per.MCMC <- foreach(r=((1+(num_gene_sub_batches*(r_all-1))):(num_gene_sub_batches*r_all)),.packages=c("Rtsne","lattice","MASS","bayesm","robustbase","chron","mnormt","MCMCpack", "coda","Matrix", "mvtnorm")) %dopar% {
+         values <- list()
+         values <- main.fun(r)
+         return(list(unlist(values[[1]]),unlist(values[[2]]),unlist(values[[3]]),values[[4]],values[[5]],values[[6]])) ##z, alpha, beta, mu and Sigma
+     }
+ results.all.MCMC[[r_all]] <- results.per.MCMC
+ print(paste("End of batch ",r_all));
+ }
[1] "Beginning of batch  1"
Error in { : task 10 failed - "missing value where TRUE/FALSE needed"

I am not sure how to resolve this error. Thanks.

**Comment by sandhya212** [comment]
This error alone might not be sufficient to debug but we need to inspect your log.txt. Also could you paste here how your start_file.R is setup.

**Comment by kupadhya2** [comment]
Thanks for quick response. Please see attached log.txt file and below parameters for start_file.R
[log.txt](https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/files/2372275/log.txt)

input_file_name <- "data_for_biscuit.txt";
input_data_tab_delimited <- TRUE; #set to TRUE if the input data is tab-delimited
is_format_genes_cells <-  TRUE; #set to TRUE if input data has rows as genes and columns as cells
choose_cells <- 300; #comment if you want all the cells to be considered
choose_genes <- 500; #comment if you want all the genes to be considered
gene_batch <- 5; #number of genes per batch, therefore num_batches = choose_genes (or numgenes)/gene_batch. Max value is 150
num_iter <- 20; #number of iterations, choose based on data size.
num_cores <- 10; #number of cores for parallel processing. Ensure that detectCores() > 1 for parallel processing to work, else set num_cores to 1.
z_true_labels_avl <- TRUE; #set this to TRUE if the true labels of cells are available, else set it to FALSE. If TRUE, ensure to populate 'z_true' with the true labels in 'BISCUIT_process_data.R'
num_cells_batch <- 100; #set this to 1000 if input number of cells is in the 1000s, else set it to 100.
alpha <- 1; #DPMM dispersion parameter. A higher value spins more clusters whereas a lower value spins lesser clusters.

**Comment by sandhya212** [comment]
1) Do you have true labels for your data points?
2) From the log, it looks like your parallel processes all ran to completion. Could you check in your output folder /plot/Inferred_labels if you have any .pdfs starting with 'Final_*.*'

(Aside to your problem: you can give gene_batch a value of upto 150. A smaller value like 5 would spin too many processes. )

**Comment by kupadhya2** [comment]
I don't have true labels. I changed it to FALSE. No files in outputfolder /plot/Inferred_labels/. 
I also updated gene_batch to 150 from 5.

**Comment by sandhya212** [comment]
Yes not having true labels was the reason.

**Comment by kupadhya2** [comment]
Thanks. It worked till end after changing labels to TRUE to FALSE.

**Comment by sandhya212** [comment]
Yes. The amount of time that can be saved if a Readme file and its comments are read.

**Comment by kupadhya2** [comment]
I read it but I got confused between cell label and sample label.
