### ISSUE TITLE
10x data integration

### ISSUE THREAD

**Issue by kvshams** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#19]
Hi,
Is there any way that the 10x data can be directly integrate to this pipeline or format the 10x data for biscuit.
Thanks,
Shams

**Comment by sandhya212** [comment]
Hi Shams, 
What is the format of the 10x data? As long as you have cells x genes count matrix, you are good to go.

**Comment by kvshams** [comment]
Hi,
The cells x gene count matrix is in three separate files in 10x (Barcode, gene name & the count with the same line order). So need to convert the data first to cells x genes count matrix.

**Comment by sandhya212** [comment]
Yes right. Input to BISCUIT is a single count matrix.

**Comment by imj835** [comment]
hello, were you able to get the cells x gene count matrix sheet from the 10x files? If so pls could you let me know how you did this? Thank you,
Insiya
