### ISSUE TITLE
kmeans: more cluster centers than distinct data points

### ISSUE THREAD

**Issue by mkrzak** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#2]
Hello,
I am writing to ask for help or suggestion concerning the error as in topic. I am testing BISCUIT on the cell cycle related dataset. I am processing my single cell RNAseq dataset (not normalized, genes in rows, cells in columns) with parameters: choose_cells <- 200, choose_genes <- 300, gene_batch <- 100, num_iter <- 30, num_cells_batch <- 100, alpha <- 1. I am getting the error: kmeans: more cluster centers than distinct data points. I tried to vary three first parameters but each time getting the same error. Could you suggest me if the issue is due to the parameters or maybe to the character of dataset (Im using only cell cycle related genes). 
Best, 
Monika Krzak

**Comment by sandhya212** [comment]
Based on the error you see, it is because k-means is returning more clusters than your number of cells (i.e. 200). Try reducing alpha from 1 to 0.1 or 0.01. A higher alpha will spin more clusters whereas a lower alpha will give you lesser number of clusters. Let me know how it goes.

**Comment by mkrzak** [comment]
Dear Sandhya,
I repeat the analysis reducing alpha however Im getting the same error. The algorithm works fine with default dataset (expression_mRNA_17-Aug-2014.txt). My dataset is also txt file with gene names in rows and cell names in columns. I also varied other parameters the same result..
I see data preprocessing for default dataset (works fine) and mine are different (with issue) are different (BISCUIT_process_data.R). Do you think it can be related to the issue ?
Best,
Monika

**Comment by sandhya212** [comment]
Dear Monika,

I still do not understand what you mean by 'issue'. Also what do you mean by 'different'?
>>I see data preprocessing for default dataset (works fine) and mine are different (with issue) are different (BISCUIT_process_data.R).
Have you debugged the code to see what is happening at every line of BISCUIT_process_data.R? The .txt should not be a problem as long as it is in line with the example dataset (transposed or not).

**Comment by mkrzak** [comment]
Dear Sandhya,
I debug BISCUIT_process_data.R in order to get the full.data.1 matrix that contains counts. I noticed full.data.1 is created in different way once you process default data and once you process your data. For default data matrix (full.data.1) doesn't contain rownames and colnames. When I process mine there are. By the issue I call the kmeans error.
Best,
Monika

**Comment by sandhya212** [comment]
Dear Monica, Ok yes, the names should not be there in full.data.1. Your input should have a format similar to the default input data.
