### ISSUE TITLE
start_file.R for Zeisel data

### ISSUE THREAD

**Issue by JaredJGartner** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#20]
Hello, 

I am attempting to run Biscuit analysis on the Zeisel data before moving on to our other dataset.  I was wondering if I have the settings correct for the Start File.  From your paper you mention setting choose_cells <- 3005 and choose_genes <- 558 and in the Readme you say to set "alpha = 0.005 or less"  Are these the only changes that need to be made?

I've attempted to run the data with these settings using 16 cores with 121G of Memory.  The program runs to completion but I receive a warning messages.  I was wondering if the messages (below) are to be expected and if not how I can correct them?  Also is the time to be expected for this set up?

Thank you, 

Jared

[1] 3005
Time difference of 2.497088 hours
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In write.table(df_indicator, file = paste0(getwd(), "/",  ... :
  appending column names to file
2: In write.table("Cells selected are ", file = paste0(getwd(),  ... :
  appending column names to file
3: In write.table(((num_cells_batch * divsr + 1):(num_cells_batch *  ... :
  appending column names to file
4: In write.table(f, file = paste0(getwd(), "/debug_CM.txt"),  ... :
  appending column names to file
5: In write.table(f, file = paste0(getwd(), "/debug_CM.txt"),  ... :
  appending column names to file
6: In write.table(f, file = paste0(getwd(), "/debug_CM.txt"),  ... :
  appending column names to file
7: In write.table(f, file = paste0(getwd(), "/debug_CM.txt"),  ... :
  appending column names to file
8: In write.table(f, file = paste0(getwd(), "/debug_CM.txt"),  ... :
  appending column names to file
9: Quick-TRANSfer stage steps exceeded maximum (= 150250)
10: In write.table(df_indicator, file = paste0(getwd(), "/",  ... :
  appending column names to file
11: In write.table("Cells selected are ", file = paste0(getwd(),  ... :
  appending column names to file
12: In write.table(((num_cells_batch * divsr + 1):(num_cells_batch *  ... :
  appending column names to file
13: In sqrt(varcov) : NaNs produced
14: In sqrt(varcov) : NaNs produced
15: In sqrt(varcov) : NaNs produced

**Comment by sandhya212** [comment]
Hi Jared, 
The readme gives you all the details of how to setup the code. If that has been done correctly, then you are good to go. 
The warning messages #1-#12 are alright. I am not sure of #13-#15. How are the outputs looking?

**Comment by JaredJGartner** [comment]
Thanks for the quick response, Sandhya, I guess I was a bit confused as the settings in the Start_File.R aren't set for the Zeisel data.  So I am correct in changing the choose cells and choose genes to 3005 and 558 respectively? This is mentioned in the manuscript but not the read_me.  

As for the warnings its really #13-#50 that say "In sqrt(varcov) : NaNs produced"  and I don't believe the outputs look correct I'll attach them here and you can tell me what you think.
[Final_true_inferred_labels_imputed_X.pdf](https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016/files/2600490/Final_true_inferred_labels_imputed_X.pdf)


Jared

**Comment by sandhya212** [comment]
Hi Jared.
>So I am correct in changing the choose cells and choose genes to 3005 and 558 respectively?
>> Yes
> What was alpha set to?

**Comment by JaredJGartner** [comment]
It was set to 0.005 as is suggested in the read me.
