### ISSUE TITLE
No cluster assignment 

### ISSUE THREAD

**Issue by seqanswers** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#21]
Dear developer,

Actually I have several questions.
1. I got most of the output files and they look normal. Four clusters can be seen in the tSNE plot. Unfortunately the "cluster_posterior_probabilities.csv" shows zero for all four clusters for all cells. 
I wonder what caused this issue?
2. I really need to know the inferred cluster id for each cell. I have the "Imputed_Y_logspace.txt" and "post_imputed_tSNE_coord.txt". Is there a way to generate the cluster ids from these files?  I cannot afford to rerun it, for the reason I will mention in 3.
3. It took me two weeks to run this on a dataset with 17K genes and 20K cells on a typical Linux node.  Is it normal? Or any way to speed it up? By the way I saw some socket connection warnings.

Thank you very much!

**Comment by sandhya212** [comment]
1. Please check if you have a 'cluster_probabilities.csv' in the 'extras' folder. I am not sure why you have 0s for 'cluster_posterior_probabilities.csv'
2. #1 will give you the cluster assignments.
3. We normally run this on a HPC or on AWS. 2 weeks is not normal. The code is already parallelised and so should run faster. Please ensure you are making use of multiple cores to run this (check what num_cores is for you)

**Comment by seqanswers** [comment]
All rows of 'cluster_probabilities.csv' are like this:
	z_inferred	cluster_probability
1	1	0
2	1	0
3	1	0
4	1	0
5	1	0
6	1	0

All rows of 'cluster_posterior_probabilities.csv' are like this:
	V1	V2	V3	V4
1	0	0	0	0
2	0	0	0	0
3	0	0	0	0
4	0	0	0	0
5	0	0	0	0
6	0	0	0	0

**Comment by seqanswers** [comment]
>print(num_cores)
30

By the way, below I listed some typical warnings. 
> warnings()
1: In write.table(df_indicator, file = paste0(getwd(), "/",  ... :
  appending column names to file
4: In extends(target[[i]], defined[[i]], fullInfo = TRUE) :
  closing unused connection 32 (<-localhost.localdomain:11661)
34: In sqrt(varcov) : NaNs produced

**Comment by seqanswers** [comment]
Since I did not get the cluster assignment from 'cluster_posterior_probabilities.csv', is there any ways I can get them based on other files like "Imputed_Y_logspace.txt" and "post_imputed_tSNE_coord.txt" by ad hoc clustering for example? In particular  I haven't closed the R console, so any variables or data frames are still available to me if I can derive the cluster assignment from them.  Can you please advise me?

**Comment by sandhya212** [comment]
The cells are not ordered based on their classes in the "Imputed_Y_logspace.txt" and "post_imputed_tSNE_coord.txt". The idea is to maintain the same cell order that the user started with. 

Was the input count matrix log normalised already?
