### ISSUE TITLE
Memory usage of biscuit

### ISSUE THREAD

**Issue by zji90** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#23]
Hi,
Just wondering what's the typical memory usage for biscuit on a dataset with around 4000 genes and 3000 cells? I've been running into memory issues all the time.
 Thanks!

**Comment by sandhya212** [comment]
We have tested the code on AWS r4.16xlarge model (see under Memory-optimised here: https://aws.amazon.com/ec2/instance-types/) and have run upto 25K genes.
