### ISSUE TITLE
Question concerning MCMC convergence 

### ISSUE THREAD

**Issue by mkrzak** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#5]
Hello,
I have a question concerning MCMC convergence. I run the example data and I wish to plot the iteration versus number of clusters. With default parameters there should be three MCMC running in parallel so I assume I have to 3 plots of convergences. Is there any output that I can access the number of clusters for each iteration? I see something it in the algorithm (nr of clusters are used in the loop to produce tsne plots for each iteration) however Im not sure if I can access those values..I would be grateful for help!
Best,
Monika

**Comment by sandhya212** [comment]
You can find intermediate plots of your data in plots/Inferred_labels_per_step_per_batch. A step is one MCMC iteration and a batch is one of the three batches, in your case. The different colours per plot will indicate number of clusters in that iteration for that batch of genes. 
In the end of every batch i.e. after burn-in, the last plot is computed and saved in plots/Inferred_labels

**Comment by mkrzak** [comment]
Dear Sandhya,
Thank you for your answer. I understand the meaning of the above plots. I am asking about the accessibility of the number of clusters for each iteration in each batch, if they are assigned to any values or I have to do it manually in the code in order to access them after running the program. I want to obtain the plot of MCMC convergence similar to the one in the supplementary materials of the BISCUIT paper: firgure S4 (https://www.c2b2.columbia.edu/danapeerlab/html/pub/prabhakaran16-supp.pdf).
Best, Monika

**Comment by sandhya212** [comment]
Ok, so we are not pulling out trace plots in this version of the code. But you are more than welcome to code it though. 

At the moment only the final number of clusters is collected via results.per.MCMC (line 597) in BISCUIT_IMM_Gibbs_MCMC_parallel.R.

**Comment by mkrzak** [comment]
ok, thank Sandhya for your prompt replies! Best, Monika
