### ISSUE TITLE
F-measure computation

### ISSUE THREAD

**Issue by pedrofale** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#6]
Hello,

How do you compute the F-measure shown in Figure 6 of your paper? In the supplementary text you talk about  creating "a binary vector h encoding the ’true’ z of each cell". How do you do this binarization?

**Comment by sandhya212** [comment]
If you have the true and inferred class for each cell, where the latter is corrected via the stable matching algorithm, then you have now 2 vectors (each with length = #cells) eligible for computing the F-measure. This is the basic idea. 
To compute the F-measure when you have a large number of cells, we decided to binarise the vector for a faster linear search. #number of correctly-labelled cells = #1s in this binary vector.
