### ISSUE TITLE
BISCUIT performance on Zeisel dataset

### ISSUE THREAD

**Issue by mkrzak** [sandhya212/BISCUIT_SingleCell_IMM_ICML_2016#8]
Dear Sandhya,

I have question concerning the run of BISCUIT on Zeisel dataset (558 genes, 3005 cells) that you present in the article. How long it took ? Did you parallelize the run with number of gene batches , if yes how many you chose ? 

Best,
Monika

**Comment by sandhya212** [comment]
Dear Monika, 

Yes we did this via the parallelised code. I have used a gene_batch of 50 or 100 for this. The code was run on a AWS EC2 r4.16xlarge instance. It took under an hour to run. 
Please let me know if these answer your questions.

Regards,
Sandhya

**Comment by mkrzak** [comment]
Dear Sandhya,
Yes, thank you for your prompt reply!
Best,
Monika
